# Generated by Django 2.0.6 on 2018-07-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20180710_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
