# Generated by Django 2.0.6 on 2018-06-17 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.FloatField()),
                ('type', models.CharField(choices=[('fish', 'Fish'), ('meat', 'Meat')], max_length=40)),
                ('delivery_address', models.TextField()),
                ('company_name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('processed', 'PROCESSED'), ('completed', 'COMPLETED')], default='pending', max_length=20)),
            ],
        ),
    ]
